RedisExchangeAPI.Web/Controllers/HashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Web.Services;

namespace RedisExchangeAPI.Web.Controllers
{
    public class HashTypeController : BaseController
    {
        private string hashKey = "Sozluk";
        public HashTypeController(RedisService redisService):base(redisService){
        
        }
        public IActionResult Index()
        {
            Dictionary<string,string> dictionary = new Dictionary<string,string>();

            db.HashGetAll(hashKey).ToList().ForEach(x =>
            {

                dictionary.Add(x.Name.ToString(),x.Value.ToString());

            });

            return View(dictionary);
        }


        public IActionResult Add(string name,string value)
        {
            db.HashSet(hashKey,name,value);
            
            return RedirectToAction("Index");   
        }


        public IActionResult DeleteItem(string name)
        {
            db.HashDelete(hashKey,name);
            
            return RedirectToAction("Index");   
        }
    }
}

RedisExchangeAPI.Web/Views/HashType/Index.cshtml
@model Dictionary<string,string>
@{
    ViewData["Title"] = "Index";
}


<h1>Index</h1>




<form method="post" asp-action="Add" asp-controller="HashType" enctype="application/x-www-form-urlencoded">


    <input type="text" name="name" />
    <input type="text" name="value" />

    <button type="submit">gönder</button>


</form>

@foreach (var item in Model)
{

    <h1>@item.Key --> @item.Value <a asp-action="DeleteItem" asp-route-name="@item.Key">sil</a> </h1>

}